### ISSUE TITLE
Crate doesn't build

### ISSUE THREAD

**Issue by ijsnow** [dioxus-community/dioxus-resize-observer#2]
I'm getting this compiler error when I add this crate to my project:

```
Checking dioxus-resize-observer v0.1.0 (https://github.com/dioxus-community/dioxus-resize-observer#481585f6)
error[E0599]: no method named `get_raw_element` found for reference `&dioxus::events::MountedData` in the current scope
  --> /Users/isaacsnow/.cargo/git/checkouts/dioxus-resize-observer-aa5596352ec22ab9/481585f/src/lib.rs:91:10
   |
90 | /     mounted
91 | |         .get_raw_element()
   | |         -^^^^^^^^^^^^^^^ method not found in `&MountedData`
   | |_________|
   |
```

Here's the relevant parts of my Cargo.toml:

```toml
[dependencies]
dioxus = "0.4.3"
dioxus-desktop = "0.4.3"
dioxus-resize-observer = { git = "https://github.com/dioxus-community/dioxus-resize-observer" }
dioxus-use-mounted = { git = "https://github.com/matthunz/dioxus-use-mounted" }
```

Any idea whats going wrong? I see in this crates Cargo.toml that it uses the git repository for dioxus instead of crates but the function is available on the version I'm using according to docs.rs. Is there a plan to move to the crates.io hosted version of the crate?
